[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
e7l_s_protocol = "632M5HzWKtu4CgihaQmUNjEBxo1x6THsHfuuGXGNDWEw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
