[features]
seeds = false

[programs.devnet]
e7l_s_protocol = "FisiUgsgCrjcwzDDrdoqTpjVizLNiEij73hrTgfUSwvi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
rps = "https://solana-devnet.g.alchemy.com/v2/TfbtD6EL_PnoozBG4Jti517RS0Fivanm"
wallet = "./keys/E1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


