[features]
seeds = false
skip-lint = false

[programs.devnet]
e7l_s_protocol = "FisiUgsgCrjcwzDDrdoqTpjVizLNiEij73hrTgfUSwvi"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./keys/E1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
